### ISSUE TITLE
Bundler could not find compatible versions for gem "activerecord"

### ISSUE THREAD

**Issue by poloten4ik** [radar/searcher#5]
Hi, I'm trying to use the rails4's branch. I added this line in my gemfile : 

`gem 'searcher', :git => "git://github.com/radar/searcher", branch: 'rails_4'`

When I'm trying to do `bundle install`, I have this error : 

```
Bundler could not find compatible versions for gem "activerecord":
  In snapshot (Gemfile.lock):
    activerecord (4.0.0)

  In Gemfile:
    searcher (>= 0) ruby depends on
      activerecord (= 4.0.0.beta) ruby
```
Is there something to do?
Thanks!

**Comment by radar** [comment]
Last commit to that branch was 5 years ago. Please try using the master branch instead.
